import type { Metadata } from "next";
import { Geist, Geist_Mono, Press_Start_2P, VT323 } from "next/font/google";
import "./globals.css";
import { CookiesProvider } from "next-client-cookies/server";
import { AppProvider } from "@/providers/AppContext";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const minecraftFont = Press_Start_2P({
    weight: "400",
    variable: "--font-minecraft",
    subsets: ["latin", "latin-ext"],
    display: "swap",
});

const minecraftFallbackFont = VT323({
    weight: "400",
    variable: "--font-minecraft-fallback",
    subsets: ["latin", "vietnamese"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "Đăng ký học phần",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} ${minecraftFont.variable} ${minecraftFallbackFont.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <AppProvider>
                    <CookiesProvider>
                        {children}
                    </CookiesProvider>
                </AppProvider>
            </body>
        </html>
    );
}
