import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CookiesProvider } from "next-client-cookies/server";
import { AppProvider } from "@/providers/AppContext";
import Header from "@/components/Header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Đăng ký học phần",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <AppProvider>
                    <CookiesProvider>
                        <div className="min-h-screen bg-[#f1f4f6] text-slate-700 font-sans flex flex-col">
                            <Header />

                            {children}
                        </div>
                    </CookiesProvider>
                </AppProvider>
            </body>
        </html>
    );
}
