import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/providers/AppContext";
import Header from "@/components/Header";

const beVietnamPro = Be_Vietnam_Pro({
    variable: "--font-be-vietnam-pro",
    subsets: ["vietnamese", "latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Đăng ký học phần",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="vi"
            className={`${beVietnamPro.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <Header />
                <AppProvider>
                    {children}
                </AppProvider>
            </body>
        </html>
    );
}
